USE SOSGAME;

CREATE TABLE IF NOT EXISTS CHARACTERS(
	`id` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`id_default_stats` INT UNSIGNED NOT NULL,
	`id_stats_updater` TINYINT UNSIGNED NOT NULL,
	`id_outfit` SMALLINT UNSIGNED NOT NULL,
	`is_temp` BOOLEAN NOT NULL,
	`name` CHAR(63) NOT NULL,
	`targets` TINYINT UNSIGNED NOT NULL,
	`range` ENUM("any", "first") NOT NULL,
	`size_in_team` TINYINT UNSIGNED NOT NULL,
	`cost` MEDIUMINT UNSIGNED NOT NULL,
	`coins` SMALLINT UNSIGNED NOT NULL,
	`lvl_min` SMALLINT UNSIGNED NOT NULL,
	`lvl_max` SMALLINT UNSIGNED
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS WEAPONS_FOR_CHARACTERS(
	`id_character` SMALLINT UNSIGNED NOT NULL,
	`id_typeitem` TINYINT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_character`, `id_typeitem`)
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS PROMOTIONS_CHARACTERS(
	`id_character` SMALLINT UNSIGNED NOT NULL,
	`id_next_character` SMALLINT UNSIGNED NOT NULL,
	`cost` MEDIUMINT UNSIGNED NOT NULL,
	`coins` SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_character`, `id_next_character`)
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS OUTFITS(
	`id` SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` CHAR(63) NOT NULL,
	`dir` CHAR(63) NOT NULL
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS OUTFITS_TO_BUY(
	`id_character` SMALLINT UNSIGNED NOT NULL,
	`id_outfit` SMALLINT UNSIGNED NOT NULL,
	`coins` SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_character`, `id_outfit`)
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS OWNED_OUTFITS(
	`id_user` INT UNSIGNED NOT NULL,
	`id_outfit` SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_user`, `id_outfit`)
);

INSERT INTO OUTFITS VALUES (1, "default", "knight"), (2, "default", "knight2");

INSERT INTO CHARACTERS VALUES
(1, 1, 1, 1, TRUE, "Rycerz", 1, "first", 1, 1, 0, 1, null),
(2, 1, 3, 2, TRUE, "Złocisty Rycerz", 1, "first", 1, 1, 0, 1, null);
