USE SOSGAME;

CREATE TABLE IF NOT EXISTS HEROES(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`id_character` INT UNSIGNED NOT NULL,
	`id_stats` INT UNSIGNED NOT NULL,
	`lvl` SMALLINT UNSIGNED NOT NULL,
	`exp` SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS EQ_HEROES(
	`id` INT UNSIGNED NOT NULL,
	`id_item` INT UNSIGNED NOT NULL,

	PRIMARY KEY(`id`, `id_item`)
);
