CREATE DATABASE IF NOT EXISTS SOSGAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE SOSGAME;

CREATE TABLE IF NOT EXISTS SERVERS(
	`id` TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`name` CHAR(63) NOT NULL,
	`max_generals` TINYINT UNSIGNED NOT NULL,
	`exp_multiplier` SMALLINT UNSIGNED NOT NULL
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS ARTICLES(
	`id` MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`id_user` INT UNSIGNED NOT NULL,
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`header` VARCHAR(255) NOT NULL,
	`content` TEXT NOT NULL
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS SESSION_STORAGE(
	`id_connection` INT UNSIGNED NOT NULL,
	`id_player` INT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_connection`, `id_player`)
) ENGINE = MEMORY;

INSERT INTO SERVERS VALUES
(null, "Standard", 3, 500),
(null, "Second", 3, 1000);
