USE SOSGAME;

CREATE TABLE IF NOT EXISTS USERS(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`id_options` INT UNSIGNED NOT NULL,
	`permission` ENUM("normal", "mod", "admin", "root") NOT NULL,
	`mail` VARCHAR(255) NOT NULL UNIQUE,
	`login` VARCHAR(63) NOT NULL UNIQUE,
	`password` TEXT NOT NULL,
	`coins` MEDIUMINT UNSIGNED NOT NULL,
	`ip` CHAR(15) NOT NULL,
	`verified` BOOLEAN NOT NULL,
	`start_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`last_login_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`description` VARCHAR(511) NOT NULL,
	`avatar` VARCHAR(63) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOUGHT_GENERALS_PRESETS(
	`id_user` INT UNSIGNED NOT NULL,
	`id_character` SMALLINT UNSIGNED NOT NULL,

	PRIMARY KEY(`id_user`, `id_character`)
);

CREATE TABLE IF NOT EXISTS USERS_TO_DELETE(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`link` VARCHAR(255) NOT NULL,
	`end_date` DATETIME
);

CREATE TABLE IF NOT EXISTS USERS_TO_ACTIVATION(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`link` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS_CONFIRM_EMAILS(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`link` VARCHAR(255) NOT NULL,
	`new_mail` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLAYERS(
	`id` INT UNSIGNED NOT NULL,
	`id_server` TINYINT UNSIGNED NOT NULL,
	`id_general` INT UNSIGNED NOT NULL,
	`last_login_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(`id`, `id_server`, `id_general`)
);

CREATE TABLE IF NOT EXISTS OPTIONS(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`soundVolume` TINYINT UNSIGNED NOT NULL,
	`effectVolume` TINYINT UNSIGNED NOT NULL,
	`soundMute` BOOLEAN NOT NULL,
	`chatMute` BOOLEAN NOT NULL,
	`chatMutePm` BOOLEAN NOT NULL,
	`pvpAble` BOOLEAN NOT NULL,
	`saveInterface` BOOLEAN NOT NULL,
	`unsetInvitations` BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS BANS_IP(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`ip` CHAR(15) NOT NULL,
	`end_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BANNED_USERS(
	`id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`id_user` INT UNSIGNED NOT NULL,
	`end_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS VALUES (1, 1, "root", "admin@sosgame.pl", "root", "$2y$10$QWFT6PUiVVe456m4hrVAMOF7a4P0Uj/xSi9YRXlfLfkCtUQU3Lg96", 0, "", true, DEFAULT, DEFAULT, '', '');
INSERT INTO USERS VALUES (2, 1, "root2", "admin@sosgame2.pl", "root2", "$2y$10$QWFT6PUiVVe456m4hrVAMOF7a4P0Uj/xSi9YRXlfLfkCtUQU3Lg96", 0, "", true, DEFAULT, DEFAULT, '', '');
INSERT INTO OPTIONS VALUES (1, 30, 30, false, false, false, false, true, false);
